=== DGI-UoM/UoMIslandora/workflow_client/workflow.xsd
<xsd:schema xmlns="http://www.islandora.ca" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.islandora.ca" elementFormDefault="qualified" >
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Islandora Workflow Schema
    </xsd:documentation>
  </xsd:annotation>
  
  <xsd:element name="workflow" type="workflowType"/>

  <xsd:complexType name="workflowType">
    <xsd:sequence>
      <xsd:element name="process" type="processType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="processType">
    <xsd:sequence>
      <xsd:element name="message" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="prereq" type="xsd:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="dependant" type="xsd:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="parameters" type="parametersType" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:normalizedString" use="required"/>
    <xsd:attribute name="name" type="xsd:normalizedString" use="required"/>
    <xsd:attribute name="state" type="xsd:normalizedString" use="required"/>
    <xsd:attribute name="attempts" type="xsd:positiveInteger"/>
    <xsd:attribute name="timestamp" type="xsd:dateTime"/>
  </xsd:complexType>

  
  <xsd:complexType name="parametersType">
    <xsd:sequence>
      <xsd:element name="parameter" type="parameterType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="parameterType">
	<xsd:simpleContent>
		<xsd:extension base="xsd:string">
			<xsd:attribute name="name" type="xsd:normalizedString" use="required"/>
		</xsd:extension>
	</xsd:simpleContent>
  </xsd:complexType>
  
</xsd:schema>

=== DGI-UoM/UoMIslandora/workflow_client/test.xml
<workflow xmlns="http://www.islandora.ca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.islandora.ca http://localhost/workflow.xsd">
  
  <!-- Generates thumbnail. Initialized as completed since the 
  thumbnail has already been generated by an ingest rule.-->
  <process id="thumbnail" name="image_resize" state="completed">
    <dependant>FULL_SIZE</dependant>
    <parameters>
      <parameter name="dsid">FULL_SIZE</parameter>
      <parameter name="width">150</parameter>
      <parameter name="file_ext">jpg</parameter>
    </parameters>
  </process>
  
  <!-- Generates a "medium" sized JPG image to display. -->
  <process id="medium" name="image_resize" state="waiting">
    <dependant>FULL_SIZE</dependant>
    <parameters>
      <parameter name="dsid">FULL_SIZE</parameter>
      <parameter name="dest_ds">JPG</parameter>
      <parameter name="width">800</parameter>
      <parameter name="file_ext">jpg</parameter>
    </parameters>
  </process>
  
  <!-- Generates a jpeg2000 image that can be viewed through the Djatoka image server -->
  <process id="jp2" name="create_jp2" state="waiting">
    <dependant>FULL_SIZE</dependant>
    <parameters>
      <parameter name="dsid">FULL_SIZE</parameter>
    </parameters>
  </process>
  
  <!-- Analyzes the original image and extracts technical 
  metadata that gets stored in its own datastream -->
  <process id="jhove" name="jhove" state="waiting">
    <dependant>FULL_SIZE</dependant>
    <parameters>
      <parameter name="dsid">FULL_SIZE</parameter>
      <parameter name="dest_ds">ANSI</parameter>
    </parameters>
  </process>
  
  <!-- Updates the MODS datastream with relatedItems relationships, 
  items, and other administrative metadata that fedora knows about already -->
  <process id="mods" name="mods_extend" state="waiting">
    <dependant>MODS</dependant>.
    <parameters>
      <parameter name="dsid">MODS</parameter>
    </parameters>
  </process>
  
  <!-- Runs an XSLT on the MODS datastream to generate a new dublin core that 
  is used by fedora -->
  <process id="dc" name="xslt" state="waiting">
    <dependant>MODS</dependant>
    <prereq>mods</prereq>
    <parameters>
      <parameter name="dsid">MODS</parameter>
      <parameter name="xslt">uofm:highResImage/MODS_TO_DC</parameter>
    </parameters>
  </process>
  
  <!-- Indexes the MODS datastream by running it through an XSLT and 
  submitting it to solr. Wont execute until mods_extend has been run -->
  <process id="solr" name="solr_index" state="waiting">
    <dependant>MODS</dependant>
    <prereq>mods</prereq>
    <parameters>
      <parameter name="dsid">MODS</parameter>
      <parameter name="xslt">uofm:highResImage/MODS_TO_SOLR</parameter>
    </parameters>
  </process>
  
</workflow>
